### ISSUE TITLE
Autohide stamina bar

### ISSUE THREAD

**Issue by tacotexmex** [octacian/sprint#1]
There's been an earlier attempt at this, but never accepted and merged. The correct method for doing this is described [here](https://github.com/GunshipPenguin/sprint/pull/4#issuecomment-254095325).

**Comment by octacian** [comment]
Hmmm, I'm not sure if I completely understand this. Why does the stamina bar need to be hidden in the first place? This mod doesn't even use a stamina bar. Or are we talking one of the other existing hunger mods that implement sprinting themselves already, this being a way to make this sprinting mod be used instead?

**Comment by tacotexmex** [comment]
I don’t remember. 🙃
